---
template: 'acmwrapper.tex'
documentclass: acmart
classoption: sigconf
title: "MSR Challenge 2020 TITLE"
author:
- name: Jasmine Latendresse
  affiliation: Concordia University
  email: latendresse.jasmine@gmail.com
- name: Rabe Abdalkareem
  affiliation: Concordia University
  email: abdrabe@gmail.com
- name: Diego Elias
  affiliation: Concordia University
  email: diegoelias1@gmail.com
bibliography: msr-challenge-2020.bib
abstract: |
  This is an abstract
  
include-before: |
  ```{=latex}
  \copyrightyear{2020}
  \acmYear{2020}
  \setcopyright{none}
  \acmConference[Conference Name]{Conference info}{Date}{Location}
  \acmBooktitle{Some book title}
  \acmPrice{price}
  \acmDOI{DOI}
  \acmISBN{ISBN}
  \keywords{include keywords from abstract}
  ```
figPrefix:
  - "Fig."
  - "Figs."
secPrefix:
  - "Section"
  - "Sections"
# Enable for CSL
#csl: association-for-computing-machinery.csl
...